#!/usr/bin/env sh

set -e

echo "Build hook running"

TAG=$1
TAG=${TAG:=latest}

export COMMIT_HASH=`git rev-parse --short HEAD`
export IMAGE=zaherg/docker-etcd
export IMAGE_NAME=$IMAGE:$TAG

docker build --no-cache --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=$COMMIT_HASH \
             --build-arg IMAGE_NAME=$IMAGE_NAME \
             --build-arg DOCKER_REPO=$IMAGE \
             --file Dockerfile \
             -t $IMAGE_NAME .
