name: Publish

on: [push]

env:
  BUILD_DATE=2020-04-08T07:25:13Z
  IMAGE_NAME=zaherg/docker-etcd
  DOCKER_REPO=index.docker.io/zaherg/docker-etcd

jobs:
  build:
    name: Build Docker Image

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 15

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: push latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zaherg/docker-etcd
          tag_with_ref: true
          build_args: DOCKER_REPO=$DOCKER_REPO,IMAGE_NAME=$IMAGE_NAME,VCS_REF=$GITHUB_SHA,BUILD_DATE=$BUILD_DATE
