name: Publish

on: [push]

jobs:
  build:
    name: Build Docker Image

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 15

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: push latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zaherg/docker-etcd
          tag_with_ref: true
          add_git_labels: true
