name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build & Push

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 15

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zaherg/docker-etcd
          tag_with_ref: true
          add_git_labels: true
