name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  dockerhub:
    name: Build & Push [dockerhub]

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 15
      registry: ['docker.io', 'ghcr.io']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=zaherg/docker-etcd
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}          

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: "amd64,arm64"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build for x64
        uses: docker/build-push-action@v2
        with:
          load:  true
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          # push: ${{ github.event_name != 'pull_request' }}        
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache       

      - run: |
        docker images

      - name: trivy test
        run: |
          docker pull ghcr.io/aquasecurity/trivy:0.18.1
          docker run --rm aquasec/trivy:0.18.1 ${{ steps.buildx.outputs.name }}

      - name: Build for multi-platform
        uses: docker/build-push-action@v2
        with:
          load:  true
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          # push: ${{ github.event_name != 'pull_request' }}        
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache   
